[build-system]
requires = ["hatchling>=1.13.0,<2.0.0", "hatch-vcs"]
	build-backend = "hatchling.build"

[project]
name = "lektor-atom"
description = "Lektor plugin that generates Atom feeds."
keywords = ["Lektor", "plugin", "static-site", "blog", "atom", "rss"]
readme = "README.md"
authors = [
    {name = "A. Jesse Jiryu Davis", email = "jesse@emptysquare.net"},
]
classifiers = [
    "Environment :: Plugins",
    "Environment :: Web Environment",
    "Framework :: Lektor",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
]
dependencies = [
    "MarkupSafe",
    "feedgenerator",
]
license = {text = "MIT"}
requires-python = ">=3.12"

[project.urls]
Homepage = "https://github.com/lektor/lektor-atom"

[project.optional-dependencies]
test = [
    "pytest",
]

[project.entry-points."lektor.plugins"]
atom = "lektor_atom:AtomPlugin"
################################################################
#
# pylint
#
[tool.pylint.main]
ignore = [".git"]
load-plugins = "pylint.extensions.no_self_use"
extension-pkg-allow-list = "lxml"

[tool.pylint.format]
max-line-length = 91
max-module-lines = 2000

[tool.pylint.design]
#max-attributes = 20
#max-positional-arguments = 7   # default is 5
#max-locals = 30
#max-branches = 20
#max-nested-blocks = 8
#max-returns = 8


[tool.pylint."messages control"]
disable = [
#    "redundant-u-string-prefix",
#    "consider-using-f-string",
    "missing-docstring",
#    "unused-argument",
#    "redefined-outer-name",
#    "invalid-name",
#    "protected-access",
#    "fixme",
#    "broad-except",
#    "redefined-builtin",
#    "too-many-arguments",
#    "too-few-public-methods",
#    "too-many-public-methods",
#    "duplicate-code",
#    "unnecessary-dunder-call",
]


