[tox]
minversion = 3
envlist = 
    py
    build-dist
    lint
isolated_build = True

[testenv]
commands = pytest {posargs:tests}
deps =
    lxml
    lektor
    pytest>=6

[testenv:build-dist]
skip_install = True
deps =
    build
    twine
commands =
    python -m build .
    twine check dist/*

[testenv:lint]
base_python = py313,py312,py311,py310,py39
use_develop = true
deps =
    pylint==3.3.2
    lektor
    pytest>=6
    lxml
commands =
    pylint {posargs:tests}

[flake8]
max-line-length = 91
extend-ignore =
    # E203: Whitespace before ':'
    E203,
    # E402: Module level import not at top of file
    E402
