name: Linux tests

on:
  push:
    branches:
      - master
      - "*"
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  linux-py:
    name: Linux py${{ matrix.python }} tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - "3.13"
          - "3.12"
          - "3.11"
          - "3.10"
          - "3.9"
    steps:
      - uses: actions/checkout@v4
      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true
          cache-dependency-glob: "pyproject.toml"
      - name: Install python dependencies
        run: uv sync --group=uv --python-preference only-managed --python 3.13
      - name: Install python
        if: matrix.python != '3.13'
        run: uv python install --python-preference only-managed ${{ matrix.env }}
      - name: Setup test suite
        run: uv run tox run -vv --notest --skip-missing-interpreters false
        env:
          TOX_GH_MAJOR_MINOR: ${{ matrix.env }}
      - name: Run python tests
        run: uv run tox run --skip-pkg-install
        env:
          TOX_GH_MAJOR_MINOR: ${{ matrix.env }}
      - name: Run pre commit checks
        uses: pre-commit/action@v3.0.1
